FROM php:5.6-fpm-alpine

RUN apk update && \
    apk upgrade

RUN apk add libmcrypt-dev
RUN docker-php-ext-install mcrypt

RUN apk add libpng-dev
RUN apk add libjpeg-turbo-dev
RUN apk add freetype-dev
RUN apk add php5-soap
RUN apk add libxml2-dev

RUN docker-php-ext-configure \
        gd --with-freetype-dir=/usr/include/ \
           --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd
RUN docker-php-ext-install soap
RUN docker-php-ext-install mysql mysqli pdo_mysql

RUN rm -rf /var/cache/apk/*
